export type AgenticReadinessStepStatus = "passed" | "failed" | "blocked";

export interface AgenticReadinessStep {
  id: string;
  label: string;
  status: AgenticReadinessStepStatus;
  durationMs?: number;
  detail?: unknown;
  detailSummary?: AgenticReadinessStepDetailSummary;
}

export interface AgenticReadinessStepDetailSummary {
  command?: string;
  reason?: string;
  reportPath?: string;
  envReportPath?: string;
  nextCommand?: string;
  nextPreflightCommand?: string;
  failedEnvKeys: string[];
  blockingEvidenceIds: string[];
  evidenceChecklistCount?: number;
  endpoint2xxCount?: number;
  strictEvidenceReady?: boolean;
  brandSpecScore?: number;
  brandSpecDeliverableCount?: number;
  brandSpecAcceptanceCriteriaCount?: number;
  templateCapabilityReady?: boolean;
  templateCapabilityVariantCount?: number;
  templateCapabilityRequiredWorkflowNodes: string[];
  templateCapabilityRequiredDeliverables: string[];
  templateCapabilityCheckCount?: number;
  templateCapabilityChecksPassed?: number;
  templateCatalogTemplateCount?: number;
  templateCatalogReadyTemplateCount?: number;
  templateCatalogVariantCount?: number;
  templateCatalogWorkflowNodeTypes: string[];
  templateCatalogCheckCount?: number;
  templateCatalogChecksPassed?: number;
  brandTemplateReportOk?: boolean;
  brandTemplateRequiredKinds: string[];
  brandTemplateTemplateCount?: number;
  brandTemplateTemplateIds: string[];
  brandTemplateReadyTemplateIds: string[];
  brandTemplateKindBreakdown: Record<string, number>;
  brandTemplateKindCount?: number;
  brandTemplatePassedTemplates?: number;
  brandTemplateFailedTemplates?: number;
  brandTemplateVariantCount?: number;
  brandTemplateVariantIdsByTemplate: Record<string, string[]>;
  brandTemplateFailedVariantTemplates?: number;
  brandTemplateCapabilityTemplateCount?: number;
  brandTemplateReadyTemplateCount?: number;
  brandTemplateCapabilityVariantCount?: number;
  brandTemplatePassedChecks?: number;
  brandTemplateFailedChecks?: number;
  brandTemplateWorkflowNodeTypes: string[];
  brandTemplateWorkflowNodeTypesByTemplate: Record<string, string[]>;
  brandTemplateDeliverableKinds: string[];
  brandTemplateDeliverableIdsByTemplate: Record<string, string[]>;
  brandTemplateOutputKinds: string[];
  brandTemplateCapabilityCheckIdsByTemplate: Record<string, string[]>;
  brandTemplateMissingKinds: string[];
  brandTemplateFailedTemplateIds: string[];
  brandTemplateFailedVariantTemplateIds: string[];
  localBridgeToolCount?: number;
  localBridgeOperationCount?: number;
  localBridgeBrandTemplateCount?: number;
  localBridgeBrandTemplateReadyCount?: number;
  localBridgeBrandTemplateVariantCount?: number;
  localBridgeBrandSpecToolReady?: boolean;
  localBridgeBrandTemplateToolReady?: boolean;
  localBridgeReportOk?: boolean;
  localBridgeFailedStepIds: string[];
  localBridgeReadOnlyBrandTools: string[];
  localBridgeWriteTools: string[];
  localMcpReportOk?: boolean;
  localMcpTransportInputs: string[];
  localMcpToolCount?: number;
  localMcpToolNames: string[];
  localMcpApprovalToolNames: string[];
  localMcpApprovalSchemaOneOfCount?: number;
  localMcpOperationCount?: number;
  localMcpOperationTypes: string[];
  localMcpOperationCategories: string[];
  localMcpOperationCategoryCounts: Record<string, number>;
  localMcpOperationDrift: string[];
  localMcpBrandTemplateCount?: number;
  localMcpBrandTemplateVariantCount?: number;
  localMcpBrandTemplateReadyCount?: number;
  localMcpMuApiEnvReady?: boolean;
  localMcpMuApiRealEvidenceReady?: boolean;
  localMcpReleaseStatus?: string;
  localMcpBlockerIds: string[];
  localMcpApprovalRequestHash?: string;
  localMcpApprovalOpSummary?: string;
  localMcpApprovalOperationTypes: string[];
  localMcpApprovalWritesExecuteDirectly?: boolean;
  localMcpApprovalImportRequired?: boolean;
  localMcpApprovalRequiresUserApproval?: boolean;
  localMcpApprovalAuditOk?: boolean;
  requestHash?: string;
  opSummary?: string;
  operationTypes: string[];
}

export interface AgenticReadinessReport {
  ok: boolean;
  releasable: boolean;
  checkedAt: string;
  includeBuild: boolean;
  allowBlocked: boolean;
  requireMuApi: boolean;
  summary: {
    passed: number;
    failed: number;
    blocked: number;
  };
  steps: AgenticReadinessStep[];
}
